name: Setup EC2 instance Environment
on:
  push: {}
jobs:
  build:
    name: EC2 instance
    runs-on: ubuntu-latest
    env: 
      TFMODULE: ${{ github.workspace }}
    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v2

      - name: Setup Golang Environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Setup Terraform
        uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 1.1.5
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      - name: Terraform Lint
        run: terraform fmt -check=true -diff=true -write=false -recursive=true

      - name: Terraform Validate
        run: terraform init; terraform validate
        
      - name: Terraform tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/download/v1.4.2/tfsec-linux-amd64 -O tfsec
          chmod +x tfsec
          ./tfsec -s --exclude-downloaded-modules .

      - name: Cache Golang Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go- 

      - name: Get Golang Dependencies
        working-directory: ${{ env.TFMODULE }}/test
        run: |
         go mod tidy
         
      - name: Run Go Test
        working-directory: ${{ env.TFMODULE }}/test
        run: go test -v -timeout 30m
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
